### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by ghost** [ElectroFlameOfficial/gd-ios-tools#1]
Iphone 7 ios 15.4 doesn't currently work. It's a pre release so Im not mad in the slightest. Hope you can figure this out soon!

**Comment by efwxx** [comment]
I'm currently working on fixing this but progress is slow as of right now due to personal issues. Might release another hotfix as a prerelease for testing.

**Comment by MikaKC** [comment]
I sadly have the same issue, I would've liked to plat GD on my iPhone 8 but yeah, I hope this get fixed :).

**Comment by efwxx** [comment]
This has since been fixed.
